# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jkauppi <jkauppi@student.hive.fi>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/23 13:35:19 by jkauppi           #+#    #+#              #
#    Updated: 2022/08/02 18:36:23 by jkauppi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:3.16.1
RUN apk add --no-cache vim
ENTRYPOINT [ "vim" ]

# docker build -t vim .
# docker run -it --rm vim
